//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enum.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب.
        /// </summary>
        public static string AC_Account {
            get {
                return ResourceManager.GetString("AC_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند.
        /// </summary>
        public static string AC_Journal {
            get {
                return ResourceManager.GetString("AC_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب.
        /// </summary>
        public static string AccountId {
            get {
                return ResourceManager.GetString("AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده اضافه.
        /// </summary>
        public static string AddData {
            get {
                return ResourceManager.GetString("AddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده اضافه 1.
        /// </summary>
        public static string AddData1 {
            get {
                return ResourceManager.GetString("AddData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده اضافه 2.
        /// </summary>
        public static string AddData2 {
            get {
                return ResourceManager.GetString("AddData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده اضافه 3.
        /// </summary>
        public static string AddData3 {
            get {
                return ResourceManager.GetString("AddData3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تسویه.
        /// </summary>
        public static string AffectiveAmount {
            get {
                return ResourceManager.GetString("AffectiveAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست مبالغ.
        /// </summary>
        public static string AmountList {
            get {
                return ResourceManager.GetString("AmountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ApiId {
            get {
                return ResourceManager.GetString("ApiId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ موجودی.
        /// </summary>
        public static string BalanceAmount {
            get {
                return ResourceManager.GetString("BalanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب.
        /// </summary>
        public static string BankAccountNO {
            get {
                return ResourceManager.GetString("BankAccountNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کانال اصلی.
        /// </summary>
        public static string BaseChannelId {
            get {
                return ResourceManager.GetString("BaseChannelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امنیت.
        /// </summary>
        public static string BE_AccessList {
            get {
                return ResourceManager.GetString("BE_AccessList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری.
        /// </summary>
        public static string BE_BusinessEntity {
            get {
                return ResourceManager.GetString("BE_BusinessEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیکربندی.
        /// </summary>
        public static string BE_Config {
            get {
                return ResourceManager.GetString("BE_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس.
        /// </summary>
        public static string BE_Profile {
            get {
                return ResourceManager.GetString("BE_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مشتری.
        /// </summary>
        public static string BE_Type {
            get {
                return ResourceManager.GetString("BE_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری.
        /// </summary>
        public static string BId {
            get {
                return ResourceManager.GetString("BId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبض.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد قبض.
        /// </summary>
        public static string BillCount {
            get {
                return ResourceManager.GetString("BillCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع قبض.
        /// </summary>
        public static string BillSum {
            get {
                return ResourceManager.GetString("BillSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مشتری.
        /// </summary>
        public static string BTypeId {
            get {
                return ResourceManager.GetString("BTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ مالی.
        /// </summary>
        public static string BusinessDate {
            get {
                return ResourceManager.GetString("BusinessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string CellNumber {
            get {
                return ResourceManager.GetString("CellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش شماره.
        /// </summary>
        public static string CM_CellPrefix {
            get {
                return ResourceManager.GetString("CM_CellPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صنف.
        /// </summary>
        public static string CM_Guild {
            get {
                return ResourceManager.GetString("CM_Guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اپراتور سیم کارت.
        /// </summary>
        public static string CM_Operator {
            get {
                return ResourceManager.GetString("CM_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شرکت.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزییات.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام لاتین شرکت.
        /// </summary>
        public static string EnCompanyName {
            get {
                return ResourceManager.GetString("EnCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام لاتین.
        /// </summary>
        public static string EnFName {
            get {
                return ResourceManager.GetString("EnFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی لاتین.
        /// </summary>
        public static string EnLName {
            get {
                return ResourceManager.GetString("EnLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد خطا.
        /// </summary>
        public static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع خطا.
        /// </summary>
        public static string ErrorType {
            get {
                return ResourceManager.GetString("ErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع خطا.
        /// </summary>
        public static string ErrorTypeText {
            get {
                return ResourceManager.GetString("ErrorTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد ناموفق.
        /// </summary>
        public static string FailedCount {
            get {
                return ResourceManager.GetString("FailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب مبدا.
        /// </summary>
        public static string FwBId {
            get {
                return ResourceManager.GetString("FwBId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FwPrCode {
            get {
                return ResourceManager.GetString("FwPrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FWRefNo {
            get {
                return ResourceManager.GetString("FWRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صنف.
        /// </summary>
        public static string GuildId {
            get {
                return ResourceManager.GetString("GuildId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راهنما.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا.
        /// </summary>
        public static string IBAN {
            get {
                return ResourceManager.GetString("IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادمین.
        /// </summary>
        public static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IsPostPaid {
            get {
                return ResourceManager.GetString("IsPostPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رزرو شده.
        /// </summary>
        public static string IsReserved {
            get {
                return ResourceManager.GetString("IsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند.
        /// </summary>
        public static string Journal {
            get {
                return ResourceManager.GetString("Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ سند.
        /// </summary>
        public static string JournalDate {
            get {
                return ResourceManager.GetString("JournalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند.
        /// </summary>
        public static string JournalId {
            get {
                return ResourceManager.GetString("JournalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین شناسه.
        /// </summary>
        public static string LastId {
            get {
                return ResourceManager.GetString("LastId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین شناسه خرید.
        /// </summary>
        public static string LastResNum {
            get {
                return ResourceManager.GetString("LastResNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین تراکنش.
        /// </summary>
        public static string LastTxnDate {
            get {
                return ResourceManager.GetString("LastTxnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ دریافت.
        /// </summary>
        public static string LocalDate_Rx {
            get {
                return ResourceManager.GetString("LocalDate_Rx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ارسال.
        /// </summary>
        public static string LocalDate_TX {
            get {
                return ResourceManager.GetString("LocalDate_TX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ محلی.
        /// </summary>
        public static string LocalDateTime {
            get {
                return ResourceManager.GetString("LocalDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه محلی.
        /// </summary>
        public static string LocalId {
            get {
                return ResourceManager.GetString("LocalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال درخواست.
        /// </summary>
        public static string LocalSerial {
            get {
                return ResourceManager.GetString("LocalSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف مبلغ.
        /// </summary>
        public static string MaxAmount {
            get {
                return ResourceManager.GetString("MaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همراه اول.
        /// </summary>
        public static string MCI {
            get {
                return ResourceManager.GetString("MCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد همراه اول.
        /// </summary>
        public static string MCICount {
            get {
                return ResourceManager.GetString("MCICount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع همراه اول.
        /// </summary>
        public static string MCISum {
            get {
                return ResourceManager.GetString("MCISum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کف مبلغ.
        /// </summary>
        public static string MinAmount {
            get {
                return ResourceManager.GetString("MinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ویرایش.
        /// </summary>
        public static string ModifiedOn {
            get {
                return ResourceManager.GetString("ModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MTI {
            get {
                return ResourceManager.GetString("MTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایرانسل.
        /// </summary>
        public static string MTN {
            get {
                return ResourceManager.GetString("MTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد ایرانسل.
        /// </summary>
        public static string MTNCount {
            get {
                return ResourceManager.GetString("MTNCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع ایرانسل.
        /// </summary>
        public static string MTNSum {
            get {
                return ResourceManager.GetString("MTNSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ گروهی.
        /// </summary>
        public static string MultiChage {
            get {
                return ResourceManager.GetString("MultiChage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست شماره ها.
        /// </summary>
        public static string NumberList {
            get {
                return ResourceManager.GetString("NumberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NumberListLen {
            get {
                return ResourceManager.GetString("NumberListLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اپراتور.
        /// </summary>
        public static string OperatorId {
            get {
                return ResourceManager.GetString("OperatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ اصلی.
        /// </summary>
        public static string OriginalAmount {
            get {
                return ResourceManager.GetString("OriginalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس دیگر.
        /// </summary>
        public static string OtherAddress {
            get {
                return ResourceManager.GetString("OtherAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل دیگر.
        /// </summary>
        public static string OtherEmail {
            get {
                return ResourceManager.GetString("OtherEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اپراتورهای دیگر.
        /// </summary>
        public static string OtherOperator {
            get {
                return ResourceManager.GetString("OtherOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن دیگر.
        /// </summary>
        public static string OtherTell {
            get {
                return ResourceManager.GetString("OtherTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صنف سرشاخه.
        /// </summary>
        public static string ParentCM_Guild {
            get {
                return ResourceManager.GetString("ParentCM_Guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرشاخه.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ.
        /// </summary>
        public static string PinCharge {
            get {
                return ResourceManager.GetString("PinCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد شارژ پین.
        /// </summary>
        public static string PinChargeCount {
            get {
                return ResourceManager.GetString("PinChargeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع شارژ پین.
        /// </summary>
        public static string PinChargeSum {
            get {
                return ResourceManager.GetString("PinChargeSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد محصول.
        /// </summary>
        public static string PrCode {
            get {
                return ResourceManager.GetString("PrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش شماره.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه عمومی.
        /// </summary>
        public static string PublicId {
            get {
                return ResourceManager.GetString("PublicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول صف.
        /// </summary>
        public static string QLen {
            get {
                return ResourceManager.GetString("QLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReferenceId {
            get {
                return ResourceManager.GetString("ReferenceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مرجع.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RefNumId {
            get {
                return ResourceManager.GetString("RefNumId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مرجع.
        /// </summary>
        public static string RefrenceNumber {
            get {
                return ResourceManager.GetString("RefrenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ثبت.
        /// </summary>
        public static string RegCode {
            get {
                return ResourceManager.GetString("RegCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string RegDate {
            get {
                return ResourceManager.GetString("RegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ درخواست.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سفارش.
        /// </summary>
        public static string RequestSerial {
            get {
                return ResourceManager.GetString("RequestSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reserve2 {
            get {
                return ResourceManager.GetString("Reserve2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reserve3 {
            get {
                return ResourceManager.GetString("Reserve3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reserve4 {
            get {
                return ResourceManager.GetString("Reserve4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reserve5 {
            get {
                return ResourceManager.GetString("Reserve5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره رزرو.
        /// </summary>
        public static string ReserveNumber {
            get {
                return ResourceManager.GetString("ReserveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Resevre1 {
            get {
                return ResourceManager.GetString("Resevre1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پاسخ.
        /// </summary>
        public static string ResponseCode {
            get {
                return ResourceManager.GetString("ResponseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام پاسخ.
        /// </summary>
        public static string ResponseMsg {
            get {
                return ResourceManager.GetString("ResponseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReverseTxn {
            get {
                return ResourceManager.GetString("ReverseTxn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایتل.
        /// </summary>
        public static string Rightel {
            get {
                return ResourceManager.GetString("Rightel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد رایتل.
        /// </summary>
        public static string RightelCount {
            get {
                return ResourceManager.GetString("RightelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع رایتل.
        /// </summary>
        public static string RightelSum {
            get {
                return ResourceManager.GetString("RightelSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان مشخص شده.
        /// </summary>
        public static string ScheduleTime {
            get {
                return ResourceManager.GetString("ScheduleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وضعیت.
        /// </summary>
        public static string StatusCode {
            get {
                return ResourceManager.GetString("StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان انگلیسی.
        /// </summary>
        public static string TitleEn {
            get {
                return ResourceManager.GetString("TitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string TitleFa {
            get {
                return ResourceManager.GetString("TitleFa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ مستقیم.
        /// </summary>
        public static string TopUp {
            get {
                return ResourceManager.GetString("TopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد شارژ مستقیم.
        /// </summary>
        public static string TopUpCount {
            get {
                return ResourceManager.GetString("TopUpCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع شارژ مستقیم.
        /// </summary>
        public static string TopUpSum {
            get {
                return ResourceManager.GetString("TopUpSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ کل.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل درخواست.
        /// </summary>
        public static string TotalRequest {
            get {
                return ResourceManager.GetString("TotalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TraceEntityId {
            get {
                return ResourceManager.GetString("TraceEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد مجاز تلاش.
        /// </summary>
        public static string TryCount {
            get {
                return ResourceManager.GetString("TryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش.
        /// </summary>
        public static string TxnAmount {
            get {
                return ResourceManager.GetString("TxnAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز تراکنش.
        /// </summary>
        public static string TxnDate {
            get {
                return ResourceManager.GetString("TxnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه تراکنش.
        /// </summary>
        public static string TxnMonth {
            get {
                return ResourceManager.GetString("TxnMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تراکنش.
        /// </summary>
        public static string TxnType {
            get {
                return ResourceManager.GetString("TxnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تراکنش.
        /// </summary>
        public static string TxStatus {
            get {
                return ResourceManager.GetString("TxStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نوع.
        /// </summary>
        public static string TypeCode {
            get {
                return ResourceManager.GetString("TypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
