//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_JournalDetail
    {
        public long Id { get; set; }
        public long JournalId { get; set; }
        public long AccountId { get; set; }
        public decimal TxnAmount { get; set; }
        public decimal BalanceAmount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
