//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class aspnet_ActionInRole
    {
        [Key]
        public int Id { get; set; }
        public string ActionName { get; set; }
        public int ActionId { get; set; }
        public string RoleName { get; set; }
        public string ContorolName { get; set; }
    }
}
