//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BE_BusinessEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BE_BusinessEntity()
        {
            this.BE_AccessList = new HashSet<BE_AccessList>();
            this.CM_Operator = new HashSet<CM_Operator>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string TitleFa { get; set; }
        public string TitleEn { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsActive { get; set; }
        public int GuildId { get; set; }
        public int BTypeId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<byte> TryCount { get; set; }
        public Nullable<long> LastResNum { get; set; }
        public Nullable<int> TraceEntityId { get; set; }
        public Nullable<int> RefNumId { get; set; }
        public Nullable<bool> IsReserved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BE_AccessList> BE_AccessList { get; set; }
        public virtual BE_Type BE_Type { get; set; }
        public virtual CM_Guild CM_Guild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CM_Operator> CM_Operator { get; set; }
    }
}
