//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BE_Config
    {
        public long Id { get; set; }
        public int QLen { get; set; }
        public byte NumberListLen { get; set; }
        public bool Bill { get; set; }
        public bool Purchase { get; set; }
        public bool PinCharge { get; set; }
        public bool TopUp { get; set; }
        public bool MTN { get; set; }
        public bool MCI { get; set; }
        public bool Rightel { get; set; }
        public bool OtherOperator { get; set; }
        public bool Balance { get; set; }
        public bool MultiChage { get; set; }
        public bool ReverseTxn { get; set; }
        public Nullable<bool> Firewall { get; set; }
        public Nullable<bool> Resevre1 { get; set; }
        public Nullable<bool> Reserve2 { get; set; }
        public Nullable<bool> Reserve3 { get; set; }
        public Nullable<bool> Reserve4 { get; set; }
        public Nullable<bool> Reserve5 { get; set; }
        public Nullable<bool> UniqueRequest { get; set; }
    }
}
