//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BE_Profile
    {
        public long Id { get; set; }
        public string CompanyName { get; set; }
        public string EnCompanyName { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string EnFName { get; set; }
        public string EnLName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string NationalCode { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string RegCode { get; set; }
        public string OtherTell { get; set; }
        public string OtherEmail { get; set; }
        public string OtherAddress { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
