//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeOrder
    {
        public long Id { get; set; }
        public long ReferenceNumber { get; set; }
        public long RequestSerial { get; set; }
        public long ChargePoolId { get; set; }
        public long BId { get; set; }
        public Nullable<byte> DeviceType { get; set; }
        public string Address { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> cpId { get; set; }
    }
}
