//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Contacts
    {
        public int Id { get; set; }
        public string CellNumber { get; set; }
        public string Title { get; set; }
        public bool IsActive { get; set; }
        public bool IsAdmin { get; set; }
    }
}
