//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Messages_Operator
    {
        public int Id { get; set; }
        public Nullable<int> MessageID { get; set; }
        public byte OperatorID { get; set; }
        public int ResponseCode { get; set; }
        public string ResponseMessage { get; set; }
        public bool HasRetryChance { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CM_Messages CM_Messages { get; set; }
    }
}
