//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSrvMain2Entitieseeeeeee : DbContext
    {
        public MSrvMain2Entitieseeeeeee()
            : base("name=MSrvMain2Entitieseeeeeee")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
          //  throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AC_Account> AC_Account { get; set; }
        public virtual DbSet<BE_AccessList> BE_AccessList { get; set; }
        public virtual DbSet<BE_BusinessEntity> BE_BusinessEntity { get; set; }
        public virtual DbSet<BE_Config> BE_Config { get; set; }
        public virtual DbSet<BE_Counter> BE_Counter { get; set; }
        public virtual DbSet<BE_Profile> BE_Profile { get; set; }
        public virtual DbSet<BE_Type> BE_Type { get; set; }
        public virtual DbSet<CM_CellPrefix> CM_CellPrefix { get; set; }
        public virtual DbSet<CM_Contacts> CM_Contacts { get; set; }
        public virtual DbSet<CM_Guild> CM_Guild { get; set; }
        public virtual DbSet<CM_Messages> CM_Messages { get; set; }
        public virtual DbSet<CM_Operator> CM_Operator { get; set; }
        public virtual DbSet<Infra_Config> Infra_Config { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
