//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoolFailed
    {
        public long RowId { get; set; }
        public long NewFileId { get; set; }
        public Nullable<byte> Type { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
