//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public int Id { get; set; }
        public string Province_Code { get; set; }
        public string Province_Title { get; set; }
        public string En_Title { get; set; }
    }
}
