//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    
    public partial class RepCheckModel
    {
        public string TBL_Name { get; set; }
        public Nullable<long> Id { get; set; }
        public long BId { get; set; }
        public string TitleFa { get; set; }
        public decimal OriginalAmount { get; set; }
        public Nullable<long> FwBId { get; set; }
        public Nullable<long> RequestSerial { get; set; }
        public Nullable<long> RefrenceNumber { get; set; }
        public Nullable<long> LocalSerial { get; set; }
        public Nullable<int> ResponseCode { get; set; }
        public string ResponseMsg { get; set; }
        public Nullable<byte> TxStatus { get; set; }
        public string AddData1 { get; set; }
        public string AddData2 { get; set; }
        public string Address { get; set; }
        public Nullable<byte> OperatorId { get; set; }
        public string OperatorTitle { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> LocalDate_TX { get; set; }
        public Nullable<System.DateTime> LocalDate_RX { get; set; }
        public Nullable<long> journalId { get; set; }
        public int? Prcode { get; set; }
        public long ReserveNumber_RequestSerial { get; set; }
        public string CURSPMSG { get; set; }



    }
}
