//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    
    public partial class SpSalesModel
    {
        public decimal Amount { get; set; }
        public long AccountID { get; set; }
        public string Customer { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<byte> OperatorId { get; set; }
        public Nullable<decimal> OriginalAmount { get; set; }
    }
}
