//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Txn_SystemInfo
    {
        public long Id { get; set; }
        public System.DateTime TxnDate { get; set; }
        public byte TxnMonth { get; set; }
        public long BId { get; set; }
        public int TopUpCount { get; set; }
        public decimal TopUpSum { get; set; }
        public int MCICount { get; set; }
        public decimal MCISum { get; set; }
        public int MTNCount { get; set; }
        public decimal MTNSum { get; set; }
        public int RightelCount { get; set; }
        public decimal RightelSum { get; set; }
        public int BillCount { get; set; }
        public decimal BillSum { get; set; }
        public int PinChargeCount { get; set; }
        public decimal PinChargeSum { get; set; }
        public int FailedCount { get; set; }
        public int TotalRequest { get; set; }
        public System.DateTime LastTxnDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
    public partial class Txn_SystemInfoD
    {
        public System.DateTime TxnDate { get; set; }
        public byte TxnMonth { get; set; }
        public long BId { get; set; }
        public int TopUpCount { get; set; }
        public decimal TopUpSum { get; set; }
        public int MCICount { get; set; }
        public decimal MCISum { get; set; }
        public int MTNCount { get; set; }
        public decimal MTNSum { get; set; }
        public int RightelCount { get; set; }
        public decimal RightelSum { get; set; }
        public int BillCount { get; set; }
        public decimal BillSum { get; set; }
        public int PinChargeCount { get; set; }
        public decimal PinChargeSum { get; set; }
        public int FailedCount { get; set; }
        public int TotalRequest { get; set; }
        public System.DateTime LastTxnDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
