//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Txn_Info
    {
        public long Id { get; set; }
        public int TxnType { get; set; }
        public int PrCode { get; set; }
        public Nullable<int> FwPrCode { get; set; }
        public long BId { get; set; }
        public Nullable<System.DateTime> LocalDate_TX { get; set; }
        public Nullable<System.DateTime> LocalDate_Rx { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime BusinessDate { get; set; }
        public Nullable<long> LocalSerial { get; set; }
        public Nullable<long> RequestSerial { get; set; }
        public decimal OriginalAmount { get; set; }
        public decimal AffectiveAmount { get; set; }
        public long FwBId { get; set; }
        public Nullable<long> RefrenceNumber { get; set; }
        public Nullable<long> FWRefNo { get; set; }
        public Nullable<int> ResponseCode { get; set; }
        public string ResponseMsg { get; set; }
        public Nullable<byte> TxStatus { get; set; }
        public string AddData1 { get; set; }
        public string AddData2 { get; set; }
        public string AddData3 { get; set; }
        public string AddDate { get; set; }
        public string Address { get; set; }
        public Nullable<byte> OperatorId { get; set; }
        public Nullable<long> JournalId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
