//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Txn_Error
    {
        public long Id { get; set; }
        public int ErrorCode { get; set; }
        public Nullable<long> BId { get; set; }
        public byte ApiId { get; set; }
        public string Address { get; set; }
        public Nullable<long> ReserveNumber { get; set; }
        public Nullable<long> ReferenceNumber { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CellNumber { get; set; }
        public string NumberList { get; set; }
        public string AmountList { get; set; }
        public Nullable<System.DateTime> LocalDateTime { get; set; }
        public string AddData { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
