//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Txn_Queue
    {
        public long Id { get; set; }
        public int MTI { get; set; }
        public int PrCode { get; set; }
        public long JournalId { get; set; }
        public byte Status { get; set; }
        public System.DateTime ScheduleTime { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> TryCount { get; set; }
    }
}
