//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_BusinessEntity
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public int GuildId { get; set; }
        public int BTypeId { get; set; }
        public string FName { get; set; }
        public string CompanyName { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<byte> TryCount { get; set; }
        public decimal BalanceAmount { get; set; }
        public bool IsPostPaid { get; set; }
        public Nullable<decimal> MinAmount { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public Nullable<int> TraceEntityId { get; set; }
        public Nullable<int> RefNumId { get; set; }
        public Nullable<long> LastResNum { get; set; }
        public string TitleFa { get; set; }
        public string Title_Typ { get; set; }
        public string Title_G { get; set; }
    }
}
