//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bko.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_SaleOrder
    {
        public long Id { get; set; }
        public long ReferenceNumber { get; set; }
        public long RequestSerial { get; set; }
        public long ChargePoolId { get; set; }
        public Nullable<byte> DeviceType { get; set; }
        public Nullable<long> pSeriral { get; set; }
        public string pPin { get; set; }
        public int OperatorId { get; set; }
        public decimal CardPrice { get; set; }
        public byte Status { get; set; }
        public long PcId { get; set; }
        public string Title { get; set; }
        public decimal PcPrice { get; set; }
        public int CardCount { get; set; }
        public long cId { get; set; }
        public long Bid { get; set; }
    }
}
